"""alter confirmation table

Revision ID: 45921f11a716
Revises: edac45753d22
Create Date: 2024-08-18 15:09:55.243319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45921f11a716'
down_revision: Union[str, None] = 'edac45753d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_confirmacao', sa.Column('con_confirmado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_confirmacao', 'con_confirmado')
    # ### end Alembic commands ###
