"""add tbl_usuario table 

Revision ID: 7f58e9b04893
Revises: 
Create Date: 2024-05-24 14:10:02.586558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f58e9b04893'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_perfil',
    sa.Column('per_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('per_nome', sa.String(), nullable=True),
    sa.Column('per_usuId', sa.Integer(), nullable=True),
    sa.Column('per_foto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('per_id')
    )
    op.create_index(op.f('ix_tbl_perfil_per_foto'), 'tbl_perfil', ['per_foto'], unique=False)
    op.create_index(op.f('ix_tbl_perfil_per_nome'), 'tbl_perfil', ['per_nome'], unique=False)
    op.create_index(op.f('ix_tbl_perfil_per_usuId'), 'tbl_perfil', ['per_usuId'], unique=False)
    op.create_table('tbl_usuario',
    sa.Column('usu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usu_email', sa.String(), nullable=False),
    sa.Column('usu_senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('usu_id'),
    sa.UniqueConstraint('usu_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_usuario')
    op.drop_index(op.f('ix_tbl_perfil_per_usuId'), table_name='tbl_perfil')
    op.drop_index(op.f('ix_tbl_perfil_per_nome'), table_name='tbl_perfil')
    op.drop_index(op.f('ix_tbl_perfil_per_foto'), table_name='tbl_perfil')
    op.drop_table('tbl_perfil')
    # ### end Alembic commands ###
