"""Mensagem da revisão

Revision ID: cb61f04eb73c
Revises: 60fd756f433b
Create Date: 2024-08-11 14:42:10.825908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb61f04eb73c'
down_revision: Union[str, None] = '60fd756f433b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_usuario', sa.Column('fcm_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_usuario', 'fcm_token')
    # ### end Alembic commands ###
