"""alter confirmation

Revision ID: edac45753d22
Revises: cb61f04eb73c
Create Date: 2024-08-18 15:06:27.508284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edac45753d22'
down_revision: Union[str, None] = 'cb61f04eb73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_confirmacao', sa.Column('con_perfilId', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_confirmacao', 'con_perfilId')
    # ### end Alembic commands ###
